apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocrandd-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocrandd-pod
  template:
    metadata:
      labels:
        app: pocrandd-pod
    spec:
      containers:
      - name: pocrandd
        image: qaacrpocrandd.azurecr.io/pocrandd:v1
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
