apiVersion: apps/v1
kind: Deployment
metadata:
  name: pocrandd-deploy1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pocrandd-pod1
  template:
    metadata:
      labels:
        app: pocrandd-pod1
    spec:
      containers:
      - name: pocrandd
        image: qaacrpocrandd.azurecr.io/pocrandd:v1
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pocrandd-svc1
spec:
  type: LoadBalancer
  selector:
    app: pocrandd-pod
  ports:
  - port: 80
